# Generated by Django 5.2.7 on 2025-11-12 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_articulo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruequeSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('SUGERIDO', 'Sugerido'), ('ACEPTADO', 'Aceptado por todos'), ('RECHAZADO', 'Rechazado por alguien')], default='SUGERIDO', max_length=10)),
                ('detalles_cadena', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(related_name='trueques_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
