# Generated by Django 5.2.7 on 2025-11-12 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_truequesugerido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo_deseado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='myapp.articulo')),
                ('articulo_ofrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to='myapp.articulo')),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_hechas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
