# Generated by Django 5.2.7 on 2025-11-15 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_oferta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truequesugerido',
            name='usuarios_que_aceptaron',
            field=models.ManyToManyField(blank=True, related_name='trueques_aceptados', to=settings.AUTH_USER_MODEL),
        ),
    ]
